alumni_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about_us/$', views.about_us, name='about_us'),
    url(r'^team/$', views.team, name='team'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^account_info/$', views.account_info, name='account_info'),
    url(r'^search/$', views.search, name='search'),
    url(r'^user/(?P<username>\w+)/$', views.public_profile, name='public_profile'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'
urlpatterns=[
    url(r'^$',views.home,name='home'),
    url(r'^home/$',views.home,name='home'),
    url(r'^events/$', views.events, name='events'),
    url(r'^about/$', views.about_us, name='about_us'),
    url(r'^team/$', views.team, name='team'),
    url(r'^question/$', views.question, name='question'),
    #url(r'^login/$', views.hometry, name='login_ms'),
    #url(r'^gettoken/$', views.gettoken, name='gettoken'),

    #url(r'^accounts/login/$',views.register,name='register'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
    url(r'^accounts/edit_profile_manual/$', views.profile_edit_manual, name='profile_edit_manual'),
    url(r'^accounts/edit_profile_linkdin/$', views.profile_edit_linkdin, name='profile_edit_linkdin'),
    url(r'^accounts/update/$',views.update_user,name='update_user'),
    url(r'^parse/$',views.linkedin_companies_parser,name="linkedin_companies_parser"),
]

matrix/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from . import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^alumni/', include('alumni.urls',namespace='alumni')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^dimension/', include('dimension.urls',namespace='dimension')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext as translate
from django.utils.timezone import now
from django.contrib.auth.models import PermissionsMixin
from django.db import models

HOSTEL_CHOICES = (
    ('Siang','Siang'),
    ('Lohit' , 'Lohit'),
    ('Manas', 'Manas'),
    ('Dhing', 'Dhing'),
    ('Barak', 'Barak'),
    ('Umiam', 'Umiam'),
    ('Subhansari', 'Subhansari'),
    ('Dibang', 'Dibang'),
    ('Kapili', 'Kapili'),
    ('Dhansari', 'Dhansari'),
)


class AutoCreatedUpdatedMixin(models.Model):

    created_at = models.DateTimeField(
        verbose_name=translate('created at'),
        unique=False,
        null=True,
        blank=True,
        db_index=True,
    )

    updated_at = models.DateTimeField(
        verbose_name=translate('updated at'),
        unique=False,
        null=True,
        blank=True,
        db_index=True,
    )

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = now()
            self.updated_at = self.created_at
        else:
            auto_updated_at_is_disabled = kwargs.pop('disable_auto_updated_at', False)
            if not auto_updated_at_is_disabled:
                self.updated_at = now()
        super(AutoCreatedUpdatedMixin, self).save(*args, **kwargs)


class SoftDeleteMixin(models.Model):

    deleted_at = models.DateTimeField(
        verbose_name=translate('deleted at'),
        unique=False,
        null=True,
        blank=True,
        db_index=True,
    )

    class Meta:
        abstract = True

    def delete(self, using=None, keep_parents=False):
        self.deleted_at = now()
        kwargs = {
            'using': using,
        }
        if hasattr(self, 'updated_at'):
            kwargs['disable_auto_updated_at'] = True
        self.save(**kwargs)

class User(AbstractUser,AutoCreatedUpdatedMixin,SoftDeleteMixin):
    name = models.CharField(blank=False , max_length=30)

class Student(AutoCreatedUpdatedMixin,SoftDeleteMixin):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    hostel = models.CharField(max_length=100, blank=False , choices=HOSTEL_CHOICES)
    room = models.CharField(blank=False , max_length=10)
    contact = models.CharField(blank=False , max_length=10)
    roll = models.CharField(blank=False , max_length=10)

home/forms.py
from django import forms
from django.contrib.auth.models import User,Group
from alumni.models import Alumni
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    group=forms.ModelChoiceField(queryset=Group.objects.all(),required=True)
    #name = forms.CharField(max_length=30, required=True)
    name = forms.CharField(max_length=30, required=True)
    email_link=forms.EmailField(required=True)
    fb_link = forms.URLField(required=True)
    ln_link = forms.URLField(required=True)
    phone_no=forms.CharField(required=True)
    curr_work = forms.CharField(max_length=100, required=True)
    pre_work = forms.CharField(max_length=200, required=True)
    class Meta:
        model = User
        fields = ['username','name','phone_no','email_link','fb_link','ln_link','curr_work','pre_work','password','group',]

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.name = self.cleaned_data["name"]
        user.email_link = self.cleaned_data["email_link"]
        user.ln_link = self.cleaned_data["ln_link"]
        user.fb_link = self.cleaned_data["fb_link"]
        user.phone_no=self.cleaned_data["phone_no"]
        user.curr_work = self.cleaned_data["curr_work"]
        user.pre_work = self.cleaned_data["pre_work"]
        if commit:
            user.save()
        return user

home/views.py
import urllib3
import time

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404, redirect , HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group, User

from alumni.forms import ProfileForm
from alumni.models import Alumni
from .forms import UserForm

from lxml import html
import csv, os, json
import requests
from django.utils import timezone
#from selenium import webdriver
import bs4 as bs
import urllib3
#import pyrebase
from home.authhelper import get_signin_url, get_token_from_code, get_access_token
from home.outlookservice import get_me
from django.urls import reverse

# Create your views here.
def home(request):
    return render(request,'home/index.html')
def about_us(request):
    return render(request,'home/about.html')
def team(request):
    return render(request,'home/team.html')
def events(request):
    return render(request,'home/events.html')

def question(request):
    return render(request,'home/question.html')

def hometry(request):
  redirect_uri = request.build_absolute_uri(reverse('home:gettoken'))
  sign_in_url = get_signin_url(redirect_uri)
  return HttpResponse('<a href="' + sign_in_url +'">Click here to sign in and view your mail</a>')

def gettoken(request):
  auth_code = request.GET['code']
  redirect_uri = request.build_absolute_uri(reverse('home:gettoken'))
  token = get_token_from_code(auth_code, redirect_uri)
  access_token = token['access_token']
  user = get_me(access_token)
  refresh_token = token['refresh_token']
  expires_in = token['expires_in']

  # expires_in is in seconds
  # Get current timestamp (seconds since Unix Epoch) and
  # add expires_in to get expiration time
  # Subtract 5 minutes to allow for clock differences
  expiration = int(time.time()) + expires_in - 300

  # Save the token in the session
  request.session['access_token'] = access_token
  request.session['refresh_token'] = refresh_token
  request.session['token_expires'] = expiration
  return HttpResponse('User: {0}, Access token: {1}'.format(user['mail'], access_token))


'''
config = {
    'apiKey': "AIzaSyD6nWjooy2i_KwbCh79nULmmLivqwES2SU",
    'authDomain': "matrix-16ca4.firebaseapp.com",
    'databaseURL': "https://matrix-16ca4.firebaseio.com",
    'projectId': "matrix-16ca4",
    'storageBucket': "matrix-16ca4.appspot.com",
    'messagingSenderId': "497393251946"
}

firebase = pyrebase.initialize_app(config)
auth = firebase.auth()
def singIn(request):
    return render(request, "signIn.html")
def postsign(request):
    email=request.POST.get('email')
    passw = request.POST.get("pass")
    try:
        user = auth.sign_in_with_email_and_password(email,passw)
    except:
        message = "invalid cerediantials"
        return render(request,"signIn.html",{"msg":message})
    print(user)
    return render(request, "welcome.html",{"e":email})
'''

########### views for user accounts
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        email=form.cleaned_data["email_link"]
        password = form.cleaned_data['password']
        name = form.cleaned_data["name"]
        phone_no=form.cleaned_data["phone_no"]
        email_link=form.cleaned_data["email_link"]
        ln_link = form.cleaned_data["ln_link"]
        fb_link = form.cleaned_data["fb_link"]
        curr_work = form.cleaned_data["curr_work"]
        pre_work = form.cleaned_data["pre_work"]
        group=form.cleaned_data['group']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        my_group = Group.objects.get(name=group)
        new_Alumni=Alumni.objects.create(user=user,name=name,roll_no=username,phone_no=phone_no,email_link=email,ln_link=ln_link,fb_link=fb_link,curr_work = curr_work,prev_work=pre_work)
        new_Alumni.save()
        my_group.user_set.add(user)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'home/index.html')
    context = {
        "form": form,
    }
    return render(request, 'registration/register.html', context)

@login_required
@permission_required('polls.can_vote')
def update_user(request):
    alumni=Alumni.objects.all()
    cur_year=(timezone.now().year)/100
    for user1 in alumni:
        admi_date = (user1.roll_no) / 10000000
        user = get_object_or_404(User, username=str(user1.roll_no))
        if cur_year - admi_date <= 4:
            remove_group = Group.objects.get(name='Alumni')
            remove_group.user_set.remove(user)
            add_group = Group.objects.get(name='Students')
            add_group.user_set.add(user)
        else:
            remove_group = Group.objects.get(name='Students')
            remove_group.user_set.remove(user)
            add_group = Group.objects.get(name='Alumni')
            add_group.user_set.add(user)
    return render(request,'registration/user_updates.html',{'alumni':alumni,})

@login_required
def profile(request):
    alumni = Alumni.objects.filter(user=request.user)
    us=request.user
    no_of_posts_by_user=len(us.post_set.all())
    return render(request,'registration/profile.html',{'alumni':alumni,'no_of_posts_by_user':no_of_posts_by_user})
@login_required
def profile_edit_manual(request):
    # # driver = webdriver.Firefox(executable_path=r'your\path\geckodriver.exe')  # I actually used the chromedriver and did not test firefox, but it should work.
    # # profile_link = "https://www.linkedin.com/in/ashish-ranjan-753429136/"
    # # driver.get(profile_link)
    # # html = driver.page_source
    # # soup = bs.BeautifulSoup(html,'lxml')  # specify parser or it will auto-select for you
    # # summary = soup.find('section', {"id": "summary"})
    # # print (summary.getText())
    urlopener = urllib3.build_opener()
    urlopener.addheaders = [('User-agent', 'Mozilla/5.0')]
    sauce = urlopener.open('https://www.linkedin.com/in/deepakgouda/').read()
    #sauce = urllib3.urlopen('https://www.linkedin.com/in/ashish-ranjan-753429136/').read()
    soup=bs.BeautifulSoup(sauce,'lxml')
    print(soup)
    alumni=get_object_or_404(Alumni, user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST,instance=alumni)
        if form.is_valid():
            alumni = form.save(commit=False)
            alumni.save()
            return redirect('home:profile')
    else:
        form = ProfileForm()
    return render(request, 'registration/edit_profile.html', {'form': form,})
def profile_edit_linkdin(request):
    # # driver = webdriver.Firefox(executable_path=r'your\path\geckodriver.exe')  # I actually used the chromedriver and did not test firefox, but it should work.
    # # profile_link = "https://www.linkedin.com/in/ashish-ranjan-753429136/"
    # # driver.get(profile_link)
    # # html = driver.page_source
    # # soup = bs.BeautifulSoup(html,'lxml')  # specify parser or it will auto-select for you
    # # summary = soup.find('section', {"id": "summary"})
    # # print (summary.getText())
    urlopener = urllib3.build_opener()
    urlopener.addheaders = [('User-agent', 'Mozilla/5.0')]
    sauce = urlopener.open('https://www.linkedin.com/in/aditya-mittal-709a1162/').read()
    #sauce = urllib3.urlopen('https://www.linkedin.com/in/ashish-ranjan-753429136/').read()
    soup=bs.BeautifulSoup(sauce,'lxml')
    tag1=soup.findAll('ul')
    #data=soup.findAll('section' ,attrs={'class':'profile-section','id':'topcard'})
    # for x in soup.findAll('section' ,attrs={'class':'profile-section','id':'topcard'}):
    #     print(x)
    #data = soup.find('section', attrs={'class': 'profile-section', 'id': 'topcard'})
    name= soup.find('section' ,attrs={'class':'profile-section','id':'topcard'}).find('h1',attrs={'class':'fn'})
    final_name=name.text
    location = soup.find('section', attrs={'class': 'profile-section', 'id': 'topcard'}).find('span', attrs={'class': 'locality'})
    final_location=location.text
    skills_soup=soup.find('section', attrs={'class': 'profile-section', 'id': 'skills'}).find_all('li')
    skills=[""]*len(skills_soup)
    i=0
    for li in skills_soup:
        skills[i]=skills_soup[i].text
        i=i+1
    final_skills=skills[:len(skills_soup)-3]
    #id=data.findAll('section' ,attrs={'id':'topcard'})
    #print(soup.prettify())
    #print(soup.title)
    #print(vol)
    #print(skills[:len(vol)-3])
    #for ski in skills:
    #    print(ski)
    print(final_name)
    print(final_location)
    print(final_skills)
    alumni=get_object_or_404(Alumni, user=request.user)
    if request.method == "POST":
        form = ProfileForm(request.POST,instance=alumni)
        if form.is_valid():
            alumni = form.save(commit=False)
            alumni.save()
            return redirect('home:profile')
    else:
        form = ProfileForm()
    return render(request, 'registration/edit_profile.html', {'form': form,})

################## parsers
def linkedin_companies_parser(url):
    url="https: // www.linkedin.com / in / ashish - ranjan - 753429136 /"
    for i in range(5):
        try:
            headers = {
                'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36'
            }
            print ("Fetching :", url)
            response = requests.get(url, headers=headers, verify=False)
            formatted_response = response.content.replace('<!--', '').replace('-->', '')
            doc = html.fromstring(formatted_response)
            datafrom_xpath = doc.xpath('//code[@id="stream-promo-top-bar-embed-id-content"]//text()')
            content_about = doc.xpath('//code[@id="stream-about-section-embed-id-content"]')
            if not content_about:

home/templates/home/events.html
{% extends "home/unknownbase.html" %}
{% load staticfiles %}
{% block body %}
    <div class = " w3-padding-64 w3-container w3-center " style = "padding-right:20px">
    <h1>Events</h1>
    </div>
    <center>
    <iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=9fbob8grp3nuvl3b08ip1cd5bc%40group.calendar.google.com&amp;color=%23875509&amp;ctz=Asia%2FCalcutta" style="border-width:5" width="1000" height="800" frameborder="2" scrolling="no"></iframe>
    </center>

    
{% endblock %}

home/templates/home/index.html
{% extends "home/unknownbase.html" %}
{% load static %}
{% block style%}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
{%endblock%}
{% block body %}
    <!-- <div class="slideshow-container">

    <div class="mySlides fade">

      <img src="{% static 'home/image/bg1.jpg' %}" style="width:100%">
        <div class="text"><b>[ MATRIX ]</b></div>
    </div>

    <div class="mySlides fade">

      <img src="{% static 'home/image/bg2.jpg' %}" style="width:100%">
      <div class="text"><b>[ MATRIX ]</b></div>
    </div>

    <div class="mySlides fade">

      <img src="{% static 'home/image/bg3.jpg' %}" style="width:100%">
      <div class="text"><b>[ MATRIX ]</b></div>
    </div>

    </div>
    <br>

    <div style="text-align:center">
      <span class="dot"></span>
      <span class="dot"></span>
      <span class="dot"></span>
    </div>
    {% if user.is_authenticated %}
        <li class="dropdown s-header-v2__nav-item s-header-v2__dropdown-on-hover">
            <a href="#"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user"></i>{{ user.get_username }} <span class="g-font-size-10--xs g-margin-l-5--xs ti-angle-down"></span></a>
            <ul class="dropdown-menu s-header-v2__dropdown-menu">
                <li><a href="{% url 'home:profile' %}" class="s-header-v2__dropdown-menu-link">Profile</a></li>
                <li><a href="{% url 'logout'%}?next={{request.path}}" class="s-header-v2__dropdown-menu-link">Logout</a></li>
            </ul>
        </li>
    {% else %}
        <li><a href="{% url 'login'%}?next={{request.path}}"><i class="fa fa-lock"></i> Login</a></li>
    {% endif %}-->
    <!-- First Grid -->
    <!--<div class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1 class="w3-text-teal hvr-float-shadow">Mathematics</h1>

          <p class=" w3-padding-32 hvr-sweep-to-right">Matrix is responsible for various events and lecture series related to Mathematics. This ensures full development of students as they learn about the real life applications of their theoretical knowledge which they have gained during their curriculum.
    Lecture series by some of the greatest minds in the world, allow our students to interact and intrigue with such immensely knowledgeable people and strive to achieve research breakthroughs.
    <br>Various Events such as LaTeX workshops and other relevant resourceful workshops help our research community to present a fruitful publication of their research projects.
              Matrix is continuously planning to conduct more and more such workshops and lectures on off-syllabi topics such as Cryptography etc.</p>
        </div>

        <div class="w3-third w3-center">
          <i class="fa fa-calculator w3-padding-64 w3-text-teal hvr-bob"></i>
        </div>
      </div>
    </div>-->

    <!-- Second Grid -->
    <!--<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-third w3-center">
          <i class="fa fa-code w3-padding-64 w3-text-blue w3-margin-right hvr-bob"></i>
        </div>

        <div class="w3-twothird">
          <h1 class="w3-text-blue hvr-float-shadow">Computer Science</h1>

          <p class="w3-padding-32 hvr-sweep-to-left">Coding skills are now essential part of professional and research domains. Matrix tries to conduct events such as Coding Competitions and Hackathons to encourage students to hone their coding skills.
    For the same purpose, we try to have various workshops on web development, network management, understanding our operating system etc. too.
    </p>
        </div>
      </div>
    </div>-->

    <!-- Third Grid -->
    <!--<div class="w3-row-padding w3-padding-64 w3-container">
      <div class="w3-content">
        <div class="w3-twothird">
          <h1 class = "w3-text-deep-purple hvr-float-shadow " >Financial Engineering</h1>

          <p class="w3-padding-32 hvr-sweep-to-right1">Matrix tries to conduct events such as Virtual Stock Market (VSM), which is a very innovative idea for understanding the stock exchange. Matrix has plans for conducting various workshops such as Portfolio Management to help the community by giving an exposure of the outside exchange techniques. </p>
        </div>

        <div class="w3-third w3-center">
          <i class="fa fa-line-chart w3-padding-64 w3-text-deep-purple hvr-bob"></i>
        </div>
      </div>
    </div>




    <div class="w3-container w3-black w3-center w3-opacity w3-padding-64">
        <h1 class="w3-margin w3-xlarge">MATRIX<br>Student Body<br>Department Of Mathematics<br>IIT Guwahati</h1>
    </div>-->



    <!-- Footer -->
    <!--<footer class="w3-container w3-padding-64 w3-center w3-opacity">
      <div class="w3-xlarge w3-padding-32">
       <a href="https://www.fb.me/MatrixIITG" class="w3-hover-text-indigo"><i class="fa fa-facebook-official hvr-float"></i></a>
       <a href="#" class="w3-hover-text-indigo"><i class="fa fa-linkedin hvr-float"></i></a>
     </div>
     <p>Powered by <a>WebD@Matrix</a></p>
    </footer>
 -->
    <!-- Banner -->
      <section id="banner">
        <div class="inner">
          <img src="{% static 'assets/img/matrix1.png' %}"><br> 
          <h2 style = "font-weight: bold; color: red; display: inline;">M</h2><h3 style = "display: inline;">athematics</h3> 
          <h2 style = "font-weight: bold; color: red; display: inline;">&nbsp;A</h2><h3 style = "display: inline;">nd</h3>
          <h2 style = "font-weight: bold; color: red; display: inline;">&nbsp;T</h2><h3 style = "display: inline;">echnology</h3>
          <h2 style = "font-weight: bold; color: red; display: inline;">&nbsp;R</h2><h3 style = "display: inline;">each out for</h3>
          <h2 style = "font-weight: bold; color: red; display: inline;">&nbsp;I</h2><h3 style = "display: inline;">ndustry&nbsp;E</h3>
          <h2 style = "font-weight: bold; color: red; display: inline;">X</h2><h3 style = "display: inline;">change</h3>
          <p style = "font-size: 22px;">The student body of <a href="https://www.iitg.ernet.in/maths/">Department of Mathematics, IIT Guwahati</a></p>
        </div>
        <video autoplay loop muted playsinline src="{% static 'images/banner.mp4' %}"></video>

      </section>

    <!-- Highlights -->
      <section class="wrapper">
        <div class="inner">
          <header class="special">
            <h2>What is Matrix, exactly?</h2>
            <p>Matrix exists to provide a channel of interaction between students and the outside world, which includes professors, alumni and other institutions.</p>
          </header>
          <div class="highlights">
            <h2 style = "text-align: center">Our domains</h2>
            <section>
              <div class="w3-card-8 content">
                <header>
                  <a href="#" class="icon fa-calculator"><span class="label">Icon</span></a>
                  <h3 style = "font-weight: bold;">Mathematics</h3>
                </header>
                <p>Matrix is responsible for various events and lecture series related to Mathematics. This ensures full development of students as they learn about the real life applications of their theoretical knowledge which they have gained during their curriculum. Lecture series by some of the greatest minds in the world, allow our students to interact and intrigue with such immensely knowledgeable people and strive to achieve research breakthroughs.
                Various Events such as LaTeX workshops and other relevant resourceful workshops help our research community to present a fruitful publication of their research projects. Matrix is continuously planning to conduct more and more such workshops and lectures on off-syllabi topics such as Cryptography etc.</p>
              </div>
            </section>
            <section>
              <div class="w3-card-8 content">
                <header>
                  <a href="#" class="icon fa-code"><span class="label">Icon</span></a>
                  <h3 style = "font-weight: bold;">Computer Science</h3>
                </header>
                <p>Coding skills are now essential part of professional and research domains. Matrix tries to conduct events such as Coding Competitions and Hackathons to encourage students to hone their coding skills. For the same purpose, we try to have various workshops on web development, network management, understanding our operating system etc. too. </p>
              </div>
            </section>
            <section>
              <div class="w3-card-8 content">
                <header>
                  <a href="#" class="icon fa-line-chart"><span class="label">Icon</span></a>
                  <h3 style = "font-weight: bold;">Finance</h3>
                </header>
                <p>Matrix tries to conduct events such as Virtual Stock Market (VSM), which is a very innovative idea for understanding the stock exchange. Matrix has plans for conducting various workshops such as Portfolio Management to help the community by giving an exposure of the outside exchange techniques. </p>
              </div>
            </section>
          </div>
        </div>
      </section>

    <!-- CTA -->
      <section id="cta" class="wrapper">
        <div class="inner">
          <h2><a style = "text-decoration: none;" href="{% url 'dimension:home' %}">Dimension</a></h2>
          <p> <a style = "text-decoration: none;" href="{% url 'dimension:home' %}">Click to see more.</a>
          </p>
        </div>
      </section>

    <!-- Testimonials -->

    <!--
      <section class="wrapper">
        <div class="inner">
          <header class="special">
            <h2>Faucibus consequat lorem</h2>
            <p>In arcu accumsan arcu adipiscing accumsan orci ac. Felis id enim aliquet. Accumsan ac integer lobortis commodo ornare aliquet accumsan erat tempus amet porttitor.</p>
          </header>
          <div class="testimonials">
            <section>
              <div class="content">
                <blockquote>
                  <p>Nunc lacinia ante nunc ac lobortis ipsum. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus.</p>
                </blockquote>
                <div class="author">
                  <div class="image">
                    <img src="images/pic01.jpg" alt="" />
                  </div>
                  <p class="credit">- <strong>Jane Doe</strong> <span>CEO - ABC Inc.</span></p>
                </div>
              </div>
            </section>
            <section>
              <div class="content">
                <blockquote>
                  <p>Nunc lacinia ante nunc ac lobortis ipsum. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus.</p>
                </blockquote>
                <div class="author">
                  <div class="image">
                    <img src="images/pic03.jpg" alt="" />
                  </div>
                  <p class="credit">- <strong>John Doe</strong> <span>CEO - ABC Inc.</span></p>
                </div>
              </div>
            </section>
            <section>
              <div class="content">
                <blockquote>
                  <p>Nunc lacinia ante nunc ac lobortis ipsum. Interdum adipiscing gravida odio porttitor sem non mi integer non faucibus.</p>
                </blockquote>
                <div class="author">
                  <div class="image">
                    <img src="images/pic02.jpg" alt="" />
                  </div>
                  <p class="credit">- <strong>Janet Smith</strong> <span>CEO - ABC Inc.</span></p>
                </div>
              </div>
            </section>
          </div>
        </div>
      </section>
    -->

    <!-- Scripts -->
      <script src="{% static 'assets/js/jquery.min.js' %}"></script>
      <script src="{% static 'assets/js/browser.min.js' %}"></script>
      <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
      <script src="{% static 'assets/js/util.js' %}"></script>
      <script src="{% static 'assets/js/main.js' %}"></script>


{% endblock %}