alumni/urls.py
from django.conf.urls import url
from . import views

app_name = 'alumni'
urlpatterns = [
    url(r'^posts/$', views.post_list, name='post_list'),
    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/approval/$',views.post_approval,name="post_approval"),
    url(r'^post/(?P<pk>\d+)/approve/$', views.post_approve, name='post_approve'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
]
urlpatterns+=[
    url(r'^alumni/$', views.alumni_list, name='alumni_list'),
    url(r'^alumni/(?P<pk>\d+)/$', views.alumni_detail, name='alumni_detail'),
]

alumni_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about_us/$', views.about_us, name='about_us'),
    url(r'^team/$', views.team, name='team'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^account_info/$', views.account_info, name='account_info'),
    url(r'^search/$', views.search, name='search'),
    url(r'^user/(?P<username>\w+)/$', views.public_profile, name='public_profile'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'
urlpatterns=[
    url(r'^$',views.home,name='home'),
    url(r'^home/$',views.home,name='home'),
    url(r'^events/$', views.events, name='events'),
    url(r'^about/$', views.about_us, name='about_us'),
    url(r'^team/$', views.team, name='team'),
    url(r'^question/$', views.question, name='question'),
    #url(r'^login/$', views.hometry, name='login_ms'),
    #url(r'^gettoken/$', views.gettoken, name='gettoken'),

    #url(r'^accounts/login/$',views.register,name='register'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
    url(r'^accounts/edit_profile_manual/$', views.profile_edit_manual, name='profile_edit_manual'),
    url(r'^accounts/edit_profile_linkdin/$', views.profile_edit_linkdin, name='profile_edit_linkdin'),
    url(r'^accounts/update/$',views.update_user,name='update_user'),
    url(r'^parse/$',views.linkedin_companies_parser,name="linkedin_companies_parser"),
]

matrix/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from . import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^alumni/', include('alumni.urls',namespace='alumni')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^dimension/', include('dimension.urls',namespace='dimension')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alumni/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from home.models import User
import datetime
class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    approved_post = models.BooleanField(default=False)
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approve(self):
        self.approved_post = True
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('alumni.Post', related_name='comments',on_delete=models.CASCADE)
    author = models.CharField(max_length=200)
    text = models.CharField(max_length=300)
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=True)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

curr=datetime.datetime.now().year
YEARS=[]
for i in range(1997 ,curr+4):
    dum=[(i, str(i))]
    YEARS=YEARS+dum
class Alumni(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, blank = True)
    roll_no=models.IntegerField(default=160123005, blank=True,)
    phone_no=models.IntegerField(default=999999999, blank=True,)
    profile_img = models.ImageField(upload_to='profile_img', default="profile_img/profile.png")
    passout_year = models.IntegerField(default=2016, blank=True, choices=YEARS)
    email_link= models.EmailField(null=True)
    fb_link = models.URLField(null=True)
    ln_link = models.URLField(null=True)
    curr_work = models.CharField(max_length=100, blank = True)
    prev_work = models.CharField(max_length=200, blank = True)
    def __str__(self):
        return self.name

alumni/forms.py
from django import forms

from .models import Post,Comment,Alumni

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

class ProfileForm(forms.ModelForm):

    class Meta:
        model=Alumni
        fields=('name','profile_img','phone_no','fb_link','ln_link','email_link','curr_work','prev_work',)

alumni/views.py
from django.shortcuts import render ,get_object_or_404 ,redirect
from django.template.defaultfilters import length
from django.utils import timezone
from .models import Post,Comment,Alumni
from .forms import PostForm,CommentForm
from django.contrib.auth.decorators import login_required,permission_required
from django.db.models import Q

########### alumni view start

@login_required
def alumni_list(request):
    alumnis=Alumni.objects.all()
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    # search request result
    query = request.GET.get("q")
    if query:
        alumnis=alumnis.filter(
            Q(name__icontains=query)
            ).distinct()
        return render(request, 'alumni/alumni_list.html', {'alumnis': alumnis, 'approvalpending': approvalpending})
    return render(request, 'alumni/alumni_list.html', {'alumnis': alumnis, 'approvalpending': approvalpending})

@login_required
def alumni_detail(request ,pk):
    alumni = get_object_or_404(Alumni, pk=pk)
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    return render(request, 'alumni/alumni_details.html', {'alumni': alumni, 'approvalpending': approvalpending, })
# alumni view end

############ post view start

@login_required
def post_list(request):
    posts = Post.objects.filter(published_date__isnull=False).order_by('created_date')
    posts=posts[::-1]#for reversing the array
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.author=request.user
            comment.post=get_object_or_404(Post,pk=request.POST["butt"])
            comment.save()
            return redirect('alumni:post_list')
    else:
        form=CommentForm()        
    if len(unapprovedposts)-len(unpublishedposts)>=0:
        approvalpending=len(unapprovedposts)-len(unpublishedposts)
    else:
        approvalpending=0
    return render(request, 'post/post_list.html', {'form':form,'posts': posts,'approvalpending':approvalpending})

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user

            post.save()
            posts = Post.objects.all()
            return redirect('alumni:post_detail', pk=post.pk)
    else:
        form = PostForm()
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    return render(request, 'post/post_edit.html', {'form': form,'approvalpending':approvalpending,})

@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user_all_post=Post.objects.filter(author=request.user)
    if post in user_all_post:
        if request.method == "POST":
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                # post.published_date = timezone.now()
                post.save()
                unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
                return redirect('alumni:post_detail', pk=post.pk)
        else:
            form = PostForm(instance=post)
        unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
        unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
        if len(unapprovedposts) - len(unpublishedposts) >= 0:
            approvalpending = len(unapprovedposts) - len(unpublishedposts)
        else:
            approvalpending = 0
        return render(request, 'post/post_edit.html', {'form': form,'approvalpending':approvalpending,})
    else:
        return render(request,'post/error.html')    

@login_required
def post_detail(request,pk):
    post = get_object_or_404(Post, pk=pk)
    user_all_post=Post.objects.filter(author=request.user)
    user_post=0
    if(post in user_all_post):user_post=1
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    return render(request, 'post/post_details.html', {'post': post,'approvalpending':approvalpending,'user_post':user_post,})

@login_required
def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    posts = posts.filter(author = request.user)
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    return render(request, 'post/post_draft_list.html', {'posts': posts,'approvalpending':approvalpending,})

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('alumni:post_detail',pk=pk)

@login_required
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('alumni:post_list')

@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('alumni:post_detail' ,pk=post.pk)
    else:
        form = CommentForm()
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    return render(request, 'post/add_comment_to_post.html', {'form': form,'approvalpending':approvalpending,})

@login_required
@permission_required('polls.can_vote')
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('alumni:post_detail', pk=comment.post.pk)

@login_required
@permission_required('polls.can_vote')
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('alumni:post_detail' ,pk=comment.post.pk)

@login_required
@permission_required('polls.can_vote')
def post_approval(request):
    posts = Post.objects.filter(published_date__isnull=False).order_by('created_date')
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    return render(request, 'post/post_approval.html', {'posts': posts,'approvalpending':approvalpending,})

@login_required
@permission_required('polls.can_vote')
def post_approve(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.approve()
    posts = Post.objects.filter(published_date__isnull=False).order_by('created_date')
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    return render(request, 'post/post_list.html', {'posts': posts,'approvalpending':approvalpending,})


@login_required
@permission_required('polls.can_vote')
def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    posts = Post.objects.filter(published_date__isnull=False).order_by('created_date')
    unapprovedposts = Post.objects.filter(approved_post=False).order_by('created_date')
    unpublishedposts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    if len(unapprovedposts) - len(unpublishedposts) >= 0:
        approvalpending = len(unapprovedposts) - len(unpublishedposts)
    else:
        approvalpending = 0
    return render(request, 'post/post_list.html', {'posts': posts,'approvalpending':approvalpending})


#post view end

alumni/templates/post/add_comment_to_post.html
{% extends 'post/baseuser.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" style="text-decoration: none; background-color: #4CAF50;" class="btn btn-round btn-lg"> <span style="color: black;"><i class="icon fa-comment"></i> &nbsp;Comment</span></button>
    </form>
{% endblock %}

alumni/templates/post/baseuser.html
{% extends "home/unknownbase.html" %}
{% load staticfiles %}
{% block style%}
<title>Matrix</title>
<!--
<link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
<link rel="stylesheet" href="{% static 'css/blog.css' %}">
-->
{%endblock%}
{% block body %}
<div>
    <!-- CTA -->
      <section id="cta1" class="wrapper">
        <div class="inner">
          <h2>AlumBook</h2>
          <p>Share yourself.</p>
        </div>
      </section>
      <br> <br>
    <h1 style = "text-align: center">Feed</h2>
      <div align = "right">
      {% if user.is_authenticated %}

        {% if user.is_superuser %}
        <a href="{% url 'alumni:post_approval' %}" class = "btn-round" style="text-decoration: none; background-color: #008CBA;"><span style="color: black;"><i class="icon fa-bell-o"></i> &nbsp;View {{approvalpending}} approval(s) pending</span></a>
        {% endif %}
        <a href="{% url 'alumni:post_new' %}" class = "btn-round" style="text-decoration: none; background-color: #4CAF50;"><span style="color: black;"><i class="icon fa-plus"></i> &nbsp;Add Post</span></a>
        <a href="{% url 'alumni:post_draft_list' %}" class = "btn-round" style="text-decoration: none; background-color: #f44336;"><span style="color: black;"><i class="icon fa-edit"></i> &nbsp;View Drafts</span></a>
        <br><br><br>
     {% endif %}
    </div>

 </div>
 <div class="content container">
    <div class="row">
        <div class="col-md-8">
        {% block content %}
        {% endblock %}
        </div>
    </div>
 </div>
{% endblock %}

alumni/templates/post/error.html
<html>
<head>
	
</head>
<body>
	Sorry we didn;t get that page
</body>
</html>

alumni/templates/post/ind.html
{% extends "home/unknownbase.html" %}
{% load staticfiles %}
{% block body %}
hgfgj
{% endblock %}

alumni/templates/post/post_approval.html
{% extends 'post/baseuser.html' %}

{% block content %}
    {% for post in posts %}
        {% if not post.approved_post %}
            <div class="post">
                <div class="date">
                    {{ post.published_date }}
                </div>
                <h1><a href="{% url 'alumni:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
                <a href="{% url 'alumni:post_remove' pk=post.pk %}" class = "btn-round" style="text-decoration: none; background-color: #f44336;"><span style="color: black;"><i class="icon fa-remove"></i></span></a>
                <a href="{% url 'alumni:post_approve' pk=post.pk %}" class = "btn-round" style="text-decoration: none; background-color: #4CAF50;"><span style="color: black;"><i class="icon fa-thumbs-up"></i></span></a>
                <p>{{ post.text|linebreaksbr }}</p>
                <a href="{% url 'alumni:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
                {% for comment in post.comments.all %}
                    {% if user.is_authenticated or comment.approved_comment %}
                    <div class="comment">
                        <div class="date">
                            {{ comment.created_date }}
                            {% if not comment.approved_comment %}
                                <a class="btn btn-default" href="{% url 'alumni:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                                <a class="btn btn-default" href="{% url 'alumni:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                            {% endif %}
                        </div>
                        <strong>{{ comment.author }}</strong>
                        <p>{{ comment.text|linebreaks }}</p>
                    </div>
                    {% endif %}
                {% empty %}
                    <p>No comments here yet :(</p>
                {% endfor %}
            </div>
        {% endif %}
    {% endfor %}
{% endblock content %}

alumni/templates/post/post_details.html
{% extends 'post/baseuser.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a href="{% url 'alumni:post_publish' pk=post.pk %}" class = "btn-round" style="text-decoration: none; background-color: #4CAF50;"><span style="color: black;"><i class="icon fa-paper-plane-o"></i> &nbsp;Publish</span></a>
            <br>
        {% endif %}
        {% if user.is_authenticated %}
        <br>
        {% if users_post %}
        <a href="{% url 'alumni:post_edit' pk=post.pk %}" class = "btn-round" style="text-decoration: none; background-color: gray;"><span style="color: black;"><i class="icon fa-edit"></i> &nbsp;Edit</span></a>
        <a href="{% url 'alumni:post_remove' pk=post.pk %}" class = "btn-round" style="text-decoration: none; background-color: #f44336;"><span style="color: black;"><i class="icon fa-remove"></i> &nbsp;Remove</span></a>
        {% endif %}
        <br><br>
        {% endif %}
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
    <hr>
    <a href="{% url 'alumni:add_comment_to_post' pk=post.pk %}" class = "btn-round" style="text-decoration: none; background-color: #4CAF50;"><span style="color: black;"><i class="icon fa-comment-o"></i> &nbsp;Add comment</span></a>
    <br> <br>
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}
        <div class="comment">
            <div class="date">
                {{ comment.created_date }}
                {% if not comment.approved_comment %}
                    <a class="btn btn-default" href="{% url 'alumni:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                    <a class="btn btn-default" href="{% url 'alumni:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
            </div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
{% endblock %}

alumni/templates/post/post_draft_list.html
{% extends 'post/baseuser.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'alumni:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

alumni/templates/post/post_edit.html
{% extends 'post/baseuser.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type = "submit" class = "btn btn-lg btn-round" style="text-decoration: none; background-color: #4CAF50;"><span style="color: black;"><i class="icon fa-paper-plane"></i> &nbsp;Post</span></button>
    </form>
{% endblock %}

alumni/templates/post/post_list.html
{% extends 'post/baseuser.html' %}

{% block content %}
    {% for post in posts %}
        {% if post.approved_post %}
            <div style = "background-color: rgba(255, 255, 255, 0.7); padding: 20px; width: 1100px; height: 600px; overflow-y: scroll;" class="w3-card-8 post">
                <div align = "right" class="date">
                    {{ post.published_date }}
                </div>
                <br>
                <h2 style = "margin-bottom: 8px;" align = "center"><a href="{% url 'alumni:post_detail' pk=post.pk %}">{{ post.title }}</a></h2>
                <h4 align = "center">By: {{post.author}}</h4>
                <p>{{ post.text|linebreaks }}</p>
                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{form.as_p}}
                    <button type="submit" name="butt" class="save btn" value="{{post.pk}}">Send</button>
                </form>
                <a href="{% url 'alumni:post_detail' pk=post.pk %}">Comments: {{ post.approved_comments.count }}</a>
                {% for comment in post.comments.all %}
                    {% if user.is_authenticated or comment.approved_comment %}
                    <div class="comment">
                        <div class="date">
                            <strong>{{ comment.author }} | </strong>
                            {{ comment.created_date }}
                            {% if not comment.approved_comment %}
                                <a class="btn btn-default" href="{% url 'alumni:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                                <a class="btn btn-default" href="{% url 'alumni:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                            {% endif %}
                        </div>
                        
                        <p>{{ comment.text|linebreaks }}</p>
                    </div>
                    {% endif %}
                {% empty %}
                    <p>No comments here yet :(</p>
                {% endfor %}
            </div>
            <br><br>
        {% endif %}
    {% endfor %}
{% endblock content %}