accounts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit_profile/$',views.edit_profile,name='edit_profile'),
    url(r'^account_info/$', views.account_info, name='account_info'),
    url(r'^search/$', views.search, name='search'),
    url(r'^user/(?P<username>\w+)/$', views.public_profile, name='public_profile')
]

alumni_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about_us/$', views.about_us, name='about_us'),
    url(r'^team/$', views.team, name='team'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^account_info/$', views.account_info, name='account_info'),
    url(r'^search/$', views.search, name='search'),
    url(r'^user/(?P<username>\w+)/$', views.public_profile, name='public_profile'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'
urlpatterns=[
    url(r'^$',views.home,name='home'),
    url(r'^home/$',views.home,name='home'),
    url(r'^events/$', views.events, name='events'),
    url(r'^about/$', views.about_us, name='about_us'),
    url(r'^team/$', views.team, name='team'),
    url(r'^question/$', views.question, name='question'),
    #url(r'^login/$', views.hometry, name='login_ms'),
    #url(r'^gettoken/$', views.gettoken, name='gettoken'),

    #url(r'^accounts/login/$',views.register,name='register'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
    url(r'^accounts/edit_profile_manual/$', views.profile_edit_manual, name='profile_edit_manual'),
    url(r'^accounts/edit_profile_linkdin/$', views.profile_edit_linkdin, name='profile_edit_linkdin'),
    url(r'^accounts/update/$',views.update_user,name='update_user'),
    url(r'^parse/$',views.linkedin_companies_parser,name="linkedin_companies_parser"),
]

matrix/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from . import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^alumni/', include('alumni.urls',namespace='alumni')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^dimension/', include('dimension.urls',namespace='dimension')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime

curr=datetime.datetime.now().year
YEARS=[]
for i in range(2000, curr+4):
    dum=[(i, str(i))]
    YEARS=YEARS+dum

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    year = models.IntegerField(default=2016, blank=True, choices=YEARS)
    fb_link = models.URLField(null=True)
    ln_link = models.URLField(null=True)
    curr_work = models.CharField(max_length=100, blank = True)
    prev_work = models.CharField(max_length=200, blank = True)
    pro_img = models.ImageField(upload_to = 'images/', default="images/profile.png")


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile
import datetime

curr = datetime.datetime.now().year
YEARS = []
for i in range(2000, curr + 1):
    dum = [(i, str(i))]
    YEARS = YEARS + dum


class EditUserForm(forms.ModelForm):
    #first_name = forms.CharField(max_length=30, required=True)
    # first_name = forms.CharField(label="First Name:", max_length=30,
    #                            widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'firstname'}))
    # last_name = forms.CharField(label="Last Name:", max_length=30,
    #                            widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'lastname'}))
    # email = forms.CharField(label="Email id:", max_length=30,
    #                                   widget=forms.EmailInput(attrs={'class': 'form-control', 'name': 'emailid'}))
    #
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")
        labels = {
            "first_name": "First Name:",
            "last_name": "Last Name:",
            "email": "Email Id:"
        }

class EditProfileForm(forms.ModelForm):
    # year = forms.ChoiceField(label="Graduation Year:", choices=YEARS, required=True)
    # fb_link = forms.URLField(label="Facebook Id Link:", max_length=30,
    #                             widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'lastname'}))
    # email = forms.CharField(label="Email id:", max_length=30,
    #                         widget=forms.EmailInput(attrs={'class': 'form-control', 'name': 'emailid'}))

    class Meta:
        model = Profile
        fields = ('year', 'fb_link', 'ln_link', 'curr_work', 'prev_work', 'pro_img')
        labels = {
            "year": "Graduation Year:",
            "fb_link": "Facebook Profile Link:",
            "ln_link": "LinkedIn Profile Link:",
            "curr_work": "Currently working at:",
            "prev_work": "Previously worked at:",
            "pro_img": "Upload a recent image:"
        }


class CreateProfileForm(forms.ModelForm):
    # year = forms.ChoiceField(choices=YEARS, required=True)
    class Meta:
        model = Profile
        fields = ('year', 'fb_link', 'ln_link', 'curr_work', 'prev_work', 'pro_img')
        labels = {
            "year": "Graduation Year:",
            "fb_link": "Facebook Profile Link:",
            "ln_link": "LinkedIn Profile Link:",
            "curr_work": "Currently working at:",
            "prev_work": "Previously worked at:",
            "pro_img": "Upload a recent image:"
        }

home/forms.py
from django import forms
from django.contrib.auth.models import User,Group
from alumni.models import Alumni
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    group=forms.ModelChoiceField(queryset=Group.objects.all(),required=True)
    #name = forms.CharField(max_length=30, required=True)
    name = forms.CharField(max_length=30, required=True)
    email_link=forms.EmailField(required=True)
    fb_link = forms.URLField(required=True)
    ln_link = forms.URLField(required=True)
    phone_no=forms.CharField(required=True)
    curr_work = forms.CharField(max_length=100, required=True)
    pre_work = forms.CharField(max_length=200, required=True)
    class Meta:
        model = User
        fields = ['username','name','phone_no','email_link','fb_link','ln_link','curr_work','pre_work','password','group',]

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.name = self.cleaned_data["name"]
        user.email_link = self.cleaned_data["email_link"]
        user.ln_link = self.cleaned_data["ln_link"]
        user.fb_link = self.cleaned_data["fb_link"]
        user.phone_no=self.cleaned_data["phone_no"]
        user.curr_work = self.cleaned_data["curr_work"]
        user.pre_work = self.cleaned_data["pre_work"]
        if commit:
            user.save()
        return user

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from .models import Profile
from django.db.models import Q

from django.conf import settings

from accounts.forms import EditProfileForm, EditUserForm, CreateProfileForm


def base_response(request, body, title=None, h1=None):
    context_dict = {"base_body": body}
    if title:
        context_dict["base_title"] = title
    if h1:
        context_dict["base_h1"] = h1
    return render(request, "accounts/base.html", context_dict)


def home(request):
    return render(request, "accounts/home.html")


def team(request):
    return render(request, "accounts/team.html")


def about_us(request):
    return render(request, "accounts/about_us.html")


def login_view(request):
    if not request.user.is_authenticated:
        context_dict = {}
        if request.method == "POST":
            next_url = ""
            if "next" in request.POST:
                next_url = request.POST["next"]
            if next_url:
                context_dict["next"] = next_url
            if "username" in request.POST and "password" in request.POST and request.POST["username"] and request.POST[
                "password"]:
                username = request.POST["username"]
                password = request.POST["password"]
                context_dict["username"] = username
                user = authenticate(username=username, password=password)
                if not user:
                    context_dict["login_error"] = "Username or password is incorrect"
                elif not user.is_active:
                    context_dict["login_error"] = "Your account has been disabled. Contact support."
                else:
                    login(request, user)
                    if not next_url:
                        next_url = '/search'
                    return HttpResponseRedirect(next_url)
            else:
                context_dict["login_error"] = "You must enter both username and password"
        elif request.method == "GET":
            if "next" in request.GET and request.GET["next"]:
                context_dict["next"] = request.GET["next"]
        return render(request, "accounts/login.html", context_dict)
    else:
        return HttpResponseRedirect('/search')


def logout_view(request):
    if request.user.is_authenticated():
        logout(request)
        return HttpResponseRedirect(settings.LOGOUT_REDIRECT_URL)
    else:
        return base_response(request, "You are already logged out")


def register(request):
    if not request.user.is_authenticated:
        context_dict = {}
        if request.method == "POST":
            keys = ("username", "firstname", "lastname", "password1", "password2")
            if all((key in request.POST and request.POST[key]) for key in keys):
                username = request.POST["username"]
                password1 = request.POST["password1"]
                password2 = request.POST["password2"]
                context_dict["username"] = username
                if password1 != password2:
                    context_dict["register_error"] = "Passwords do not match"
                    form_profile = CreateProfileForm()
                    context_dict["form"] = form_profile
                elif User.objects.filter(username=username).count() > 0:
                    form_profile = CreateProfileForm()
                    context_dict["form"] = form_profile
                    context_dict["register_error"] = "A user with this username already exists"
                else:
                    user = User(username=username)
                    user.set_password(password1)
                    user.first_name = request.POST['firstname']
                    user.last_name = request.POST['lastname']
                    user.email = request.POST["email"]
                    user.save()
                    user = authenticate(username=username, password=password1)
                    print(user.profile.year)
                    form_profile = CreateProfileForm(request.POST, request.FILES, instance=user.profile)
                    if form_profile.is_valid():
                        form_profile.user = user
                        form_profile.save()
                        print("checking location")
                        print(user.profile.pro_img)
                    login(request, user)
                    return HttpResponseRedirect('/login')
            else:
                context_dict["register_error"] = "You must fill out all fields"
        else:
            form_profile = CreateProfileForm()
            context_dict["form"] = form_profile
        return render(request, "accounts/register.html", context_dict)
    else:
        return HttpResponseRedirect('/public_profile')


def account_info(request):
    return render(request, "accounts/account_info.html", {})


def edit_profile(request):
    if request.user.is_authenticated:
        context_dict = {}
        if request.method == "POST":
            form_basic = EditUserForm(request.POST, instance=request.user)
            form_add = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)
            if form_basic.is_valid() and form_add.is_valid():
                form_basic.save()
                form_add.save()
                context_dict["ep_success"] = "Profile changed successsfully"
            else:
                context_dict["ep_error"] = "Invalid data received"
        else:
            form_basic = EditUserForm(instance=request.user)
            form_add = EditProfileForm(instance=request.user.profile)
        context_dict["form_basic"] = form_basic
        context_dict["form_add"] = form_add
        return render(request, "accounts/edit_profile.html", context_dict)
    else:
        return HttpResponseRedirect('/login')


def search(request):
    if request.user.is_authenticated:
        context_dict = {}
        if request.method == "POST":
            if "query" in request.POST and request.POST["query"] != '':
                query = request.POST["query"]
                context_dict["query"] = query
                qur = Q(username__icontains=query) | Q(profile__year__icontains=query) | Q(
                    first_name__icontains=query) | Q(last_name__icontains=query) | Q(
                    profile__curr_work__icontains=query) | Q(profile__prev_work__icontains=query)
                context_dict["result"] = User.objects.filter(Q(is_superuser=False), qur)
                print(context_dict["result"])
                if len(context_dict["result"]) == 0:
                    context_dict["empty"] = "No matching user found for "
                print("hi")
                return render(request, "accounts/search_result.html", context_dict)
            else:
                context_dict["error"] = "You must enter a valid search query"
        return render(request, "accounts/search_result.html", context_dict)
    else:
        return HttpResponseRedirect('/login')


def public_profile(request, username):
    if request.user.is_authenticated:
        puser = get_object_or_404(User, username=username)
        context_dict = {"puser": puser}
        return render(request, "accounts/public_profile.html", context_dict)
    else:
        return HttpResponseRedirect('/login')

accounts/templates/accounts/about_us.html
<!DOCTYPE html>
<html>
{% load static %}
<title>Matrix</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">

<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
<link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Lato", sans-serif}
.w3-navbar,h1,button {font-family: "Montserrat", sans-serif}
.fa-anchor,.fa-coffee,.fa-calculator,.fa-line-chart,.fa-code{font-size:200px}
.alignment

</style>
<ul class="w3-navbar w3-black w3-card-2 w3-top w3-left-align w3-large">
  <li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
    <a class="w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
  </li>
  <li class="w3-left"><a href="{% url 'home' %}" class="w3-padding-large w3-hover-white">MATRIX</a></li>
  <li class="w3-right w3-hide-small " ><a href="{% url 'about_us' %}" class="w3-padding-large w3-hover-white">About us</a></li>
  <li class="w3-right w3-hide-small"><a href="{% url 'team' %}" class="w3-padding-large w3-hover-white">Team</a></li>
    <li class="w3-right w3-hide-small"><a href="https://issuu.com/matrixiitg/docs/anantha" class="w3-padding-large w3-hover-white">Anantha</a></li>
  <li class="w3-right w3-hide-small"><a href="#" class="w3-padding-large w3-hover-white">Upcoming Events</a></li>
  <li class="w3-right w3-hide-small"><a href="{% url 'login' %}" class="w3-padding-large w3-hover-white">Alumni</a></li>
  
</ul>

<!-- Navbar on small screens -->
<div id="navDemo" class="w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:51px">
  <ul class="w3-navbar w3-left-align w3-large w3-black">
  <li><a class="w3-padding-large" href="{% url 'home' %}">Home</a></li>
    <li><a class="w3-padding-large" href="{% url 'login' %}">Alumni</a></li>
    <li><a class="w3-padding-large" href="#">Upcoming Events</a></li>
      <li><a class="w3-padding-large" href="https://issuu.com/matrixiitg/docs/anantha">Anantha</a></li>
    <li><a class="w3-padding-large" href="{% url 'team' %}">Team</a></li>
    <li><a class="w3-padding-large" href="{% url 'about_us' %}">About us</a></li>
    
  </ul>
</div>




<!-- First Grid -->
<div class="w3-row-padding w3-padding-64 w3-container w3-light-grey ">
  <div class="w3-content">
    <div class = "w3-center">
      <h1 style="text-align:center;margin-left: auto;margin-right: auto" class="w3-jumbo w3-text-teal" >About</h1>
        <h5 style="text-align:center    ;margin-left: auto;margin-right: auto" class="w3-padding-32 w3-text-teal "><b>MATRIX</b> Student Body, Department of Mathematics, IIT Guwahati,
        was founded in 2008 with a vision to provide exposure for applying the mathematics and computing
            knowledge to solve the real life technical problems by organizing lectures, seminars, workshops and events.</h5>

      <h5 style="text-align:left;margin-left: 20%" class="w3-text-teal"></h5>
    </div>

  
  </div>
</div>

<!-- Second Grid -->
<div class="w3-row-padding w3-light-grey w3-padding-64 w3-container">
  <div class="w3-content">

    <div>
      <h1 style="text-align:center;margin-left: auto;margin-right: auto" class="w3-text-blue">Dimension</h1>

      <h5 class="w3-text-blue" style="text-align:center;margin-left: auto;margin-right: auto">Dimension is the annual summit of MATRIX wherein we invite dignitaries to visit our campus and address the students, about their industrial experiences, their research projects etc. In the past Dimension has had lecture series by eminent scientists from various fields such as Cryptography, Fractals, Artificial Intelligence etc.</h5>
    </div>
  </div>
</div>

<!-- Third Grid -->
<div class="w3-row-padding w3-padding-64 w3-container w3-light-grey">
  <div class="w3-content">
    <div>
      <h1 class = "w3-text-deep-purple" style="text-align:center;margin-left: auto;margin-right: auto" >Anantha</h1>
        <h5 class="w3-text-deep-purple" style="text-align:center;margin-left: auto;margin-right: auto">The Annual Magazine published by MATRIX </h5>
      <h5 class="w3-text-deep-purple" style="text-align:center;margin-left: auto;margin-right: auto">This magazine, which contains a wide range of interesting articles contributed by different people, related to latest Mathematical Research, Internship Experiences, and many more interesting articles revolving around student life at IITG, is a great medium to share ideas, innovations and experiences.</h5>
    </div>

    
  </div>
</div>





<script>
// Used to toggle the menu on small screens when clicking on the menu button
function myFunction() {
    var x = document.getElementById("navDemo");
    if (x.className.indexOf("w3-show") == -1) {
        x.className += " w3-show";
    } else {
        x.className = x.className.replace(" w3-show", "");
    }
}
var slideIndex = 0;

</script>

</body>
</html>

accounts/templates/accounts/account_info.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block title_block %}{{PROJECT_NAME}} - account{% endblock %}
{% block h1_block %}My Account{% endblock %}

{% block body_block %}

    <!--<img src='../../../{{puser.profile.pro_img.url}}' width="50%" height="50%" alt={{puser.profile.pro_img.url}}>-->
<!--<table>
    <tr><td><b>Username:</b></td><td>{{user.username}}</td></tr>
    <tr><td><b>Name:</b></td><td>{{user.get_full_name}}</td></tr>
    <tr><td><b>Email:</b></td><td>{{user.email}}</td></tr>
    <tr><td><b>Year of Graduation:</b></td><td>{{user.profile.year}}</td></tr>
    <tr><td><b>Current work:</b></td><td>{{user.profile.curr_work}}</td></tr>
    <tr><td><b>Previous works:</b></td><td>{{user.profile.prev_work}}</td></tr>
    <tr><td><b>Social links:</b></td>
        <td><a href="{{user.profile.fb_link}}" target="_blank"><img src="../../static/fb_logo.png" width="10%" height="10%" alt="Facebook"/></a></td>
        <td><a href="{{user.profile.ln_link}}" target="_blank"><img src="../../static/linkedin_logo.png" width="10%" height="10%" alt="Linkedin"/></a></td></tr>

</table>-->
    <div class="card text-center">
		<div class="card-block"><img src="../../{{user.profile.pro_img.url}}" width="100px" height="100px"></div>
            <td><a href="{% url 'accounts:public_profile' user.username %}">{{ user.username }}</a></td>
            <div class="card-block"><h3>{{ user.first_name }} {{ user.last_name }}</h3></div>
    	<div class="card-subtitle"><b>Email: </b>{{ user.email }}</div>
    	<div class="card-text"><b>Last Login: </b>{{ user.last_login }}<br>
    	<b>Graduation year: </b>{{ user.profile.year }}<br>
    	<b>Currently Works at: </b>{{ user.profile.curr_work }}<br>
    	<b>Previously Works at: </b>{{ user.profile.prev_work }}<br>
            <b>Social links:</b><a href="{{user.profile.fb_link}}" target="_blank"><img src="{% static 'fb_logo.png'%}" width="10%" height="10%" alt="Facebook"/></a>
            <a href="{{user.profile.ln_link}}" target="_blank"><img src="{% static 'linkedin_logo.png'%}" width="9%" height="9%" alt="LinkedIn"/></a>
        </div>
    	</div>
<p><a href="{% url 'accounts:edit_profile' %}">Edit profile</a></p>
<p><a href="{% url 'accounts:logout' %}">Logout</a></p>
<p><a href="{% url 'accounts:search' %}">Search</a></p>
{% endblock %}

accounts/templates/accounts/edit_profile.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block title_block %}{{PROJECT_NAME}} - Edit profile{% endblock %}
{% block h1_block %}Edit your Profile{% endblock %}

{% block body_block %}
<p style="color:red">{{ep_error}}</p>
<p style="color:green">{{ep_success}}</p>
    <div class="container">
    <div class = "row text-center" style=" margin-left: auto;margin-right: auto">
<form method="POST" action="." enctype="multipart/form-data" style=" margin-left: auto;margin-right: auto">
	{% csrf_token %}
<div style="background-color: whitesmoke;margin-left: auto;margin-right: auto;">
	{% for field in form_basic.visible_fields %}
        <div class="form-group">
            <label><b>{{field.label_tag}}</b></label>
		{{field.errors}}<br />
		{{field}}<br/>
        </div>
	{% endfor %}

    {% for field in form_add.visible_fields %}
        <div class="form-group">
            <label><b>{{field.label_tag}}</b></label>
		{{field.errors}}<br />
		{{field}}<br/>
        </div>
	{% endfor %}
</div>
	<input type="submit" name="submit" value="Submit" />
</form>
    </div>
    </div>
<br><br><br>
{#<p><a href="{% url 'accounts:change_password' %}">Change password</a></p>#}
{#<p><a href="{% url 'accounts:public_profile' user.username %}">My public profile</a></p>#}
{#<p><a href="{% url 'accounts:account_info' %}">Account info</a></p>#}
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block title_block %}{{ PROJECT_NAME }} - Login{% endblock %}


{% block body_block %}
    <p style="color:red">{{ login_error }}</p>
    <div class = "container offset-md-4 offset-sm-2 text-center">
    <div class="row text-center">
    <div class="card col-md-4 col-sm-4">
        <div class="card-header">
            {% block h1_block %}Login to {{ PROJECT_NAME }}{% endblock %}
        </div>
        <div class="card-body">
            <form method="POST" action=".">
                {% csrf_token %}
                Username:<br/>
                <input type="hidden" name="next" value="{{ next }}"/>
                <input type="text" name="username" value="{{ username }}" required="required"/>
                <br/>
                Password:<br/>
                <input type="password" name="password" required="required"/>
                <br/>
                <button type="submit">Login</button>
            </form>
            <p><a href="{% url 'register' %}">Register here</a> if you don't have an account</p>
        </div>
    </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}
{% load staticfiles %}

{% block title_block %}{{PROJECT_NAME}} - Register{% endblock %}


{% block body_block %}
<p style="color:red">{{register_error}}</p>
    <div class = "container offset-4 text-center">
    <div class="row">
    <div class="card col-auto">
    <div class="card-header text-center">{% block h1_block %}Create an Account{% endblock %}</div>
    <div class="card-body text-center">
<form method="POST" action="." enctype="multipart/form-data">
	{% csrf_token %}
	Enter Username:
	<input type="text" name="username" value="{{username}}" required="required" style="width: inherit" />
	<br><br>
    Enter Email:
	<input type="email" name="email" required="required" style="width: inherit "/>
	<br><br>
    Enter First name:
	<input type="text" name="firstname" value="{{firstname}}" required="required" />
	<br><br>
    Enter Last name:
	<input type="text" name="lastname" value="{{lastname}}" required="required" />
	<br><br>
	Enter Password:
	<input type="password" name="password1" required="required" />
	<br><br>
	Re-enter Password:
	<input type="password" name="password2" required="required" />
	<br><br>
	{{form.as_p}}

	
	<button type="submit" >Sign Up</button>
</form>
    </div>
        <p><a href="{% url 'accounts:login' %}">Login here</a> if you already have an account</p></div></div></div>
<br><br><br>{% endblock %}

accounts/templates/accounts/search_result.html
{% extends 'accounts/base.html' %}

{% block title_block %}{{PROJECT_NAME}} - account{% endblock %}
{% block h1_block %}My Account{% endblock %}

{% block body_block %}
<div class = "container-fluid col-md-6 col-md-offset-6">
<br>
<div class="row">
<form  class="form-inline" action="." method="POST">
	{% csrf_token %}
    <div class="input-group">
	<input type="text" class="form-control" size="50" placeholder="Search" name="query" required>
	<div class="input-group-btn">
        <button type="submit" class = "btn btn-danger" name="search-btn">Search</button>
    </div>
    </div>
</form>
</div>
</div>
<div class="container">
	{{error}}
	{% if result %}
		<p>Showing results for <strong>{{query}}</strong></p>
	{% else %}
		<p>{{empty}}<strong>{{query}}</strong></p>
	{% endif %}
	{% for user in result %}
		<div class="card text-center">
		<div class="card-block"><img src="../../{{user.profile.pro_img.url}}" width="50px" height="50px"></div>
            <td><a href="{% url 'public_profile' user.username %}">{{ user.username }}</a></td>
            <div class="card-block"><h3>{{ user.first_name }} {{ user.last_name }}</h3></div>
    	<div class="card-subtitle"><b>Email: </b>{{ user.email }}</div>
    	<div class="card-text"><b>Last Login: </b>{{ user.last_login }}<br>
    	<b>Graduation year: </b>{{ user.profile.year }}<br>
    	<b>Currently Works at: </b>{{ user.profile.curr_work }}<br>
    	<b>Previously Works at: </b>{{ user.profile.prev_work }}
        </div>
    	</div>
	{% endfor %}
</div>
{#<p><a href="{% url 'accounts:edit_profile' %}">Edit profile</a></p>#}
{#<p><a href="{% url 'accounts:user_list' %}">List of all users</a></p>#}
{#<p><a href="{% url 'accounts:change_password' %}">Change password</a></p>#}
    <br>
    <br>
{% endblock %}