alumni_site/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^about_us/$', views.about_us, name='about_us'),
    url(r'^team/$', views.team, name='team'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^edit_profile/$', views.edit_profile, name='edit_profile'),
    url(r'^account_info/$', views.account_info, name='account_info'),
    url(r'^search/$', views.search, name='search'),
    url(r'^user/(?P<username>\w+)/$', views.public_profile, name='public_profile'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dimension/urls.py
from django.conf.urls import url
from . import views
app_name = 'dimension'
urlpatterns=[
    url(r'^$',views.dimension,name='dimension'),
    url(r'^home/$',views.dimension,name='home'),
    url(r'^hackoverflow/$',views.hackoverflow,name='hackoverflow'),

###############################################################################################################################
    url(r'^confrence/$',views.confrence,name='confrence'),
    url(r'^try/$',views.anime,name='confrence'),
]

home/urls.py
from django.conf.urls import url
from . import views
app_name = 'home'
urlpatterns=[
    url(r'^$',views.home,name='home'),
    url(r'^home/$',views.home,name='home'),
    url(r'^events/$', views.events, name='events'),
    url(r'^about/$', views.about_us, name='about_us'),
    url(r'^team/$', views.team, name='team'),
    url(r'^question/$', views.question, name='question'),
    #url(r'^login/$', views.hometry, name='login_ms'),
    #url(r'^gettoken/$', views.gettoken, name='gettoken'),

    #url(r'^accounts/login/$',views.register,name='register'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^accounts/profile/$', views.profile, name='profile'),
    url(r'^accounts/edit_profile_manual/$', views.profile_edit_manual, name='profile_edit_manual'),
    url(r'^accounts/edit_profile_linkdin/$', views.profile_edit_linkdin, name='profile_edit_linkdin'),
    url(r'^accounts/update/$',views.update_user,name='update_user'),
    url(r'^parse/$',views.linkedin_companies_parser,name="linkedin_companies_parser"),
]

matrix/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from . import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^alumni/', include('alumni.urls',namespace='alumni')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^dimension/', include('dimension.urls',namespace='dimension')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dimension/models.py
from __future__ import unicode_literals

from django.utils.translation import ugettext as translate
from django.utils.timezone import now
from django.contrib.auth.models import PermissionsMixin
from django.db import models



class AutoCreatedUpdatedMixin(models.Model):

    created_at = models.DateTimeField(
        verbose_name=translate('created at'),
        unique=False,
        null=True,
        blank=True,
        db_index=True,
    )

    updated_at = models.DateTimeField(
        verbose_name=translate('updated at'),
        unique=False,
        null=True,
        blank=True,
        db_index=True,
    )

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = now()
            self.updated_at = self.created_at
        else:
            auto_updated_at_is_disabled = kwargs.pop('disable_auto_updated_at', False)
            if not auto_updated_at_is_disabled:
                self.updated_at = now()
        super(AutoCreatedUpdatedMixin, self).save(*args, **kwargs)


class SoftDeleteMixin(models.Model):

    deleted_at = models.DateTimeField(
        verbose_name=translate('deleted at'),
        unique=False,
        null=True,
        blank=True,
        db_index=True,
    )

    class Meta:
        abstract = True

    def delete(self, using=None, keep_parents=False):
        self.deleted_at = now()
        kwargs = {
            'using': using,
        }
        if hasattr(self, 'updated_at'):
            kwargs['disable_auto_updated_at'] = True
        self.save(**kwargs)

class Confrence(AutoCreatedUpdatedMixin,SoftDeleteMixin):
    name = models.CharField(blank=False , max_length=30)
    email = models.EmailField(blank=False)
    contact = models.CharField(blank=False , max_length=10)
    college = models.CharField(blank=False , max_length=100)
    state = models.CharField(blank=False , max_length=100)
    city = models.CharField(blank=False , max_length=100)
    transaction = models.CharField(blank=False , unique=True , max_length=100)
	
		

dimension/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from dimension.models import Confrence

class ConfrenceSignupForm(forms.ModelForm):
    class Meta:
        model = Confrence
        fields = ('name', 'contact' , 'email' , 'college','state','city','transaction')

dimension/views.py
from django.shortcuts import render
import urllib3
import time

from django.contrib.auth.decorators import login_required, permission_required
from django.shortcuts import render, get_object_or_404, redirect , HttpResponse

from .forms import *

from lxml import html
import csv, os, json
import requests
from django.utils import timezone
#from selenium import webdriver
import bs4 as bs
import urllib3
from django.urls import reverse

# Create your views here.
def home(request):
    return render(request,'dimension/index.html')
def dimension(request):
    return render(request,'dimension/index.html')
def hackoverflow(request):
    return render(request,'dimension/hackoverflow.html')

#####################################################################################

############################# 2019 Dimension Work  #########################################

def confrence(request):

    if request.method == "POST":
        form = ConfrenceSignupForm(request.POST)
        if form.is_valid():
            confrence = form.save(commit=False)
            confrence.save()
            return HttpResponse('Form submitted Successfully')

        else:
        	form = ConfrenceSignupForm()
        	errors = "form is not filled correctly"

        return render(request, 'dim2019/confrence_form.html', {'form': form ,'errors':errors})

    else:
    	form = ConfrenceSignupForm()
    	return render(request, 'dim2019/confrence_form.html', {'form': form })

def anime(request):
	return render(request, 'dim2019/layouts/try.html')

dimension/templates/dim2019/confrence_form.html
{%extends 'dim2019/layouts/blank_master.html'%}
{%load static%}
{%block title%}Registration | Confrence{%endblock%}
{%block content%}
<div class="margin-auto text-center">
	<img src="/static/img/dim.png" style="width:140px" alt="Dimension Logo"/>
</div>
<br>
<div class="row" style="margin-left:0px; margin-right: 0px;">
	<div class="col-md-3"></div>
	<div class="col-xs-12 col-md-6">
		<div class="card">

			<div class="card-body card-block">
				<form action="#" method="post" enctype="multipart/form-data" class="form-horizontal">
					

					{%csrf_token%}

					<div class="row form-group">
						<div class="col col-md-3"><label for="id_name" class=" form-control-label">Name</label></div>
						<div class="col-12 col-md-9"><input type="name" id="id_name" name="email" placeholder="" class="form-control" required></div>
					</div>

					<div class="row form-group">
						<div class="col col-md-3"><label for="id_email" class=" form-control-label">Email Address</label></div>
						<div class="col-12 col-md-9"><input type="email" id="id_email" name="email" placeholder="Enter Email" class="form-control" required><small class="help-block form-text">Please enter your email</small></div>
					</div>

					<div class="row form-group">
						<div class="col col-md-3"><label for="id_contact" class=" form-control-label">Contact</label></div>
						<div class="col-12 col-md-9 input-group">
							
							<input type="text" max-length="10" id="id_contact" name="contact" placeholder="Enter Here" class="form-control" required>
						</div>
					</div>

					<div class="row form-group">
						<div class="col col-md-3"><label for="id_college" class=" form-control-label">College</label></div>
						<div class="col-12 col-md-9"><input type="text" id="id_college" name="college" placeholder="Enter your College name" class="form-control" required></div>
					</div>

					<div class="row form-group">
						<div class="col col-md-3"><label for="id_state" class=" form-control-label">State</label></div>
						<div class="col-12 col-md-9"><input type="text"  id="id_state" name="state" class="form-control" required></div>
					</div>

					<div class="row form-group">
						<div class="col col-md-3"><label for="id_city" class=" form-control-label">City:</label></div>
						<div class="col-12 col-md-9"><input type="text" id="id_city" name="city" placeholder="Enter Here" class="form-control" required></div>
					</div>

					<div class="row form-group">
						<div class="col col-md-3"><label for="id_transaction" class=" form-control-label">Transaction ID:</label></div>
						<div class="col-12 col-md-9"><input type="text" id="id_transaction" name="transaction" placeholder="Enter Here" class="form-control" required></div>
					</div>

					

					<div class="row">
					<div class="col-xs-3 col-sm-3"></div>
					<div class="col-xs-6 col-sm-6 text-center">
						<button type="submit" name="submit" class="btn btn-success">Submit</button>
					</div>
					<div class="col-xs-3 col-sm-3"></div>
					</div>
				</form>
			</div>
		</div>
	</div>
	<div class="col-md-3"></div>
</div>
{%endblock%}

{%block script%}

{%endblock%}